# Generated by Django 5.1 on 2026-05-03 00:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Immunisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=100)),
                ('scheduled_date', models.DateField()),
                ('administered_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('due', 'Due'), ('administered', 'Administered'), ('overdue', 'Overdue')], default='due', max_length=15)),
                ('recorded_by', models.UUIDField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='immunisations', to='children.child')),
            ],
            options={
                'db_table': 'immunisation',
                'ordering': ['child', 'scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('age_band', models.CharField(choices=[('0-6m', '0 – 6 months'), ('6-12m', '6 – 12 months'), ('12-24m', '12 – 24 months'), ('24-36m', '24 – 36 months'), ('3-4y', '3 – 4 years'), ('4-5y', '4 – 5 years'), ('5-6y', '5 – 6 years')], max_length=10)),
                ('milestone_item', models.CharField(max_length=300)),
                ('achieved', models.BooleanField(default=False)),
                ('assessed_at', models.DateField()),
                ('assessed_by', models.UUIDField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milestones', to='children.child')),
            ],
            options={
                'db_table': 'milestones',
                'ordering': ['child', 'age_band'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('muac_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('head_circ_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('measurement_position', models.CharField(blank=True, choices=[('standing', 'Standing (Height)'), ('lying', 'Lying Down (Length)')], default='standing', max_length=10)),
                ('waz_score', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('haz_score', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('whz_score', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('nutritional_status', models.CharField(blank=True, choices=[('normal', 'Normal'), ('at_risk', 'At Risk'), ('mam', 'Moderate Acute Malnutrition (MAM)'), ('sam', 'Severe Acute Malnutrition (SAM)'), ('stunted', 'Stunted'), ('severely_stunted', 'Severely Stunted'), ('underweight', 'Underweight')], max_length=20)),
                ('biv_flagged', models.BooleanField(default=False)),
                ('biv_confirmed', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('embedded', 'Embedded Device'), ('simulation', 'Simulation App')], default='manual', max_length=15)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('recorded_by', models.UUIDField()),
                ('recorded_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='children.child')),
            ],
            options={
                'db_table': 'measurements',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['child', 'recorded_at'], name='measurement_child_i_430b68_idx'), models.Index(fields=['nutritional_status'], name='measurement_nutriti_526472_idx')],
            },
        ),
    ]
