# Generated by Django 5.1 on 2026-05-03 00:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referral_date', models.DateField()),
                ('reason', models.TextField()),
                ('referral_slip_url', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending — outcome unknown'), ('attended', 'Attended — parent confirmed child was taken'), ('treatment_given', 'Treatment Given — diagnosis and treatment recorded'), ('closed', 'Closed — episode complete')], default='pending', max_length=20)),
                ('health_centre_name', models.CharField(max_length=200)),
                ('outcome_date', models.DateField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('hospitalised', models.BooleanField(blank=True, null=True)),
                ('follow_up_instructions', models.TextField(blank=True)),
                ('referred_by', models.UUIDField()),
                ('followed_up_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='children.child')),
            ],
            options={
                'db_table': 'referrals',
                'ordering': ['-referral_date'],
                'indexes': [models.Index(fields=['child', 'status'], name='referrals_child_i_7b657b_idx'), models.Index(fields=['status', 'referral_date'], name='referrals_status_397128_idx')],
            },
        ),
    ]
