# Generated by Django 5.1 on 2026-05-03 00:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('centre', models.UUIDField()),
                ('date', models.DateField()),
                ('menu_description', models.TextField()),
                ('children_fed_count', models.IntegerField(default=0)),
                ('recorded_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'meals',
                'ordering': ['-date'],
                'unique_together': {('centre', 'date')},
            },
        ),
        migrations.CreateModel(
            name='NutritionProgramme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('programme_type', models.CharField(choices=[('sfp', 'Supplementary Feeding Programme (SFP) — for MAM'), ('tfp', 'Therapeutic Feeding Programme (TFP) — for SAM'), ('rutf', 'Ready-to-Use Therapeutic Food (RUTF)'), ('other', 'Other Programme')], max_length=10)),
                ('enrolment_date', models.DateField()),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('graduated', 'Graduated — child recovered'), ('defaulted', 'Defaulted — missed too many sessions'), ('transferred', 'Transferred to another centre'), ('died', 'Died'), ('ongoing', 'Ongoing')], default='ongoing', max_length=15)),
                ('recorded_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nutrition_enrolments', to='children.child')),
            ],
            options={
                'db_table': 'nutrition_programmes',
                'ordering': ['-enrolment_date'],
            },
        ),
        migrations.CreateModel(
            name='FoodIntakeFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('poor_intake', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.UUIDField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_intake_flags', to='children.child')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intake_flags', to='nutrition.meal')),
            ],
            options={
                'db_table': 'food_intake_flags',
                'ordering': ['-recorded_at'],
                'unique_together': {('child', 'meal')},
            },
        ),
    ]
