# Generated by Django 5.1 on 2026-05-03 00:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('centre', models.UUIDField()),
                ('alert_type', models.CharField(choices=[('sam_classification', 'SAM Classification'), ('mam_classification', 'MAM Classification'), ('at_risk', 'At Risk Classification'), ('stunted', 'Stunting Detected'), ('severely_stunted', 'Severe Stunting Detected'), ('underweight', 'Underweight'), ('consecutive_decline', 'Consecutive Weight Decline'), ('growth_faltering', 'Growth Faltering'), ('zscore_crossing', 'Z-Score Channel Crossing'), ('declining_muac', 'Declining MUAC Trend'), ('sudden_weight_drop', 'Sudden Weight Drop'), ('early_warning', 'Early Warning (Trend Projection)'), ('extended_absence', 'Extended Absence'), ('referral_pending', 'Referral Not Actioned'), ('nutrition_missed', 'Nutrition Programme Missed'), ('immunisation_overdue', 'Immunisation Overdue'), ('measurement_overdue', 'Measurement Overdue'), ('community_level', 'Community-Level Alert'), ('temperature_high', 'Fever Alert'), ('temperature_low', 'Hypothermia Alert')], max_length=30)),
                ('severity', models.CharField(choices=[('urgent', 'Urgent (SAM / Red)'), ('warning', 'Warning (MAM or declining trend / Yellow)'), ('information', 'Information (At Risk / Green)')], max_length=15)),
                ('explanation_en', models.TextField()),
                ('explanation_rw', models.TextField()),
                ('recommendation_en', models.TextField()),
                ('recommendation_rw', models.TextField()),
                ('trigger_data', models.JSONField()),
                ('algorithm_used', models.CharField(max_length=100)),
                ('shap_explanation', models.JSONField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active — not yet seen or actioned'), ('actioned', 'Actioned — caregiver recorded response'), ('resolved', 'Resolved — condition no longer present')], default='active', max_length=15)),
                ('actioned_by', models.UUIDField(blank=True, null=True)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('action_taken', models.TextField(blank=True)),
                ('consecutive_days_absent', models.IntegerField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='children.child')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': [models.Case(models.When(severity='urgent', then=0), models.When(severity='warning', then=1), models.When(severity='information', then=2), default=3, output_field=models.IntegerField()), '-generated_at'],
                'indexes': [models.Index(fields=['child', 'status'], name='alerts_child_i_f8e5b5_idx'), models.Index(fields=['centre', 'severity', 'status'], name='alerts_centre_d579db_idx')],
            },
        ),
    ]
