# Generated by Django 5.1 on 2026-05-03 00:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('centre', models.UUIDField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft — auto-generated, not yet reviewed'), ('approved', 'Approved — manager has signed off'), ('submitted', 'Submitted — sent to sector coordinator')], default='draft', max_length=15)),
                ('manager_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.UUIDField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'monthly_reports',
                'ordering': ['-year', '-month'],
                'unique_together': {('centre', 'month', 'year')},
            },
        ),
    ]
