# Generated by Django 5.1 on 2026-05-03 00:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FcmNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('device_token', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=200)),
                ('data', models.JSONField(default=dict)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='sent', max_length=20)),
            ],
            options={
                'db_table': 'fcm_notifications',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('msg_type', models.CharField(choices=[('sam_alert', 'SAM Alert'), ('referral_created', 'Referral Created'), ('weekly_progress', 'Weekly Progress Update'), ('absence_followup', 'Absence Follow-up'), ('batch_reminder', 'Batch Reminder')], max_length=25)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(choices=[('mock', 'Mock Provider (Demo)'), ('africas_talking', "Africa's Talking (Production)")], max_length=20)),
                ('status', models.CharField(choices=[('delivered', 'Delivered'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=15)),
                ('provider_message_id', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('child_id', models.UUIDField(blank=True, null=True)),
                ('alert_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sms_log',
                'ordering': ['-sent_at'],
            },
        ),
    ]
