# Generated by Django 5.2.7 on 2026-05-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='irerouser',
            name='requires_remote_wipe',
            field=models.BooleanField(default=False),
        ),
    ]
