# Generated by Django 5.1 on 2026-05-03 00:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='absent', max_length=10)),
                ('absence_reason', models.CharField(blank=True, choices=[('sick', 'Sick'), ('family_emergency', 'Family Emergency'), ('seasonal_farming', 'Seasonal Farming'), ('parent_travel', 'Parent Travel'), ('unknown', 'Unknown')], max_length=20)),
                ('recorded_by', models.UUIDField()),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='children.child')),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['child', 'date'], name='attendance_child_i_1c9172_idx')],
                'unique_together': {('child', 'date')},
            },
        ),
    ]
