# Generated by Django 5.1 on 2026-05-03 00:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=100)),
                ('user_id', models.UUIDField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('records_received', models.IntegerField(default=0)),
                ('records_accepted', models.IntegerField(default=0)),
                ('records_conflicted', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sync_log',
                'ordering': ['-synced_at'],
            },
        ),
    ]
