# Generated by Django 5.1 on 2026-05-03 00:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('centre_name', models.CharField(max_length=200)),
                ('sector_id', models.UUIDField()),
                ('district_id', models.UUIDField()),
                ('province', models.CharField(max_length=100)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('centre_manager_id', models.UUIDField(blank=True, null=True)),
                ('establishment_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'centres',
                'ordering': ['centre_name'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('irerero_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('guardian_name', models.CharField(max_length=200)),
                ('guardian_phone', models.CharField(max_length=20)),
                ('home_village', models.CharField(max_length=200)),
                ('enrolment_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='child_photos/')),
                ('notes', models.TextField(blank=True)),
                ('is_orphan', models.BooleanField(blank=True, null=True)),
                ('has_disability', models.BooleanField(blank=True, null=True)),
                ('hiv_exposure_status', models.BooleanField(blank=True, null=True)),
                ('chronic_conditions', models.TextField(blank=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='children.centre')),
            ],
            options={
                'db_table': 'children',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['centre', 'status'], name='children_centre__849c66_idx'), models.Index(fields=['irerero_id'], name='children_irerero_6ef835_idx')],
            },
        ),
    ]
