# Generated by Django 5.2.7 on 2026-05-12 18:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='enrolment_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
