# referrals/models.py
#
# Health centre referral tracking.
# Creates a digital referral chain — caregiver creates referral,
# parent takes PDF slip to health centre, outcome recorded on return.
# FR-054 to FR-060, SRS §8.1 Referral entity

import uuid
from django.db import models


class ReferralStatus(models.TextChoices):
    PENDING          = "pending",          "Pending — outcome unknown"
    ATTENDED         = "attended",         "Attended — parent confirmed child was taken"
    TREATMENT_GIVEN  = "treatment_given",  "Treatment Given — diagnosis and treatment recorded"
    CLOSED           = "closed",           "Closed — episode complete"


class Referral(models.Model):
    """
    One referral record per child per episode.

    Auto-populated fields at creation: child data, triggering measurements,
    referring caregiver — caregiver only adds the health centre name (FR-054).

    PDF referral slip generated by WeasyPrint and stored in media/ (FR-055).

    After 3 days Pending, a REFERRAL_PENDING alert is auto-generated by Celery (FR-057).

    follow_up_instructions stores ongoing care instructions from the health centre — FR-058.
    """
    id                    = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    child                 = models.ForeignKey(
        "children.Child", on_delete=models.PROTECT, related_name="referrals"
    )
    referral_date         = models.DateField()
    reason                = models.TextField()
    referral_slip_url     = models.CharField(max_length=500, blank=True)   # path to PDF
    status                = models.CharField(max_length=20, choices=ReferralStatus.choices,
                                             default=ReferralStatus.PENDING)
    health_centre_name    = models.CharField(max_length=200)

    # Outcome fields — FR-058
    outcome_date          = models.DateField(null=True, blank=True)
    diagnosis             = models.TextField(blank=True)
    treatment             = models.TextField(blank=True)
    hospitalised          = models.BooleanField(null=True, blank=True)
    follow_up_instructions = models.TextField(blank=True)   # FR-058 exact field

    # Audit
    referred_by           = models.UUIDField()
    followed_up_by        = models.UUIDField(null=True, blank=True)
    created_at            = models.DateTimeField(auto_now_add=True)
    updated_at            = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "referrals"
        ordering = ["-referral_date"]
        indexes  = [
            models.Index(fields=["child", "status"]),
            models.Index(fields=["status", "referral_date"]),
        ]

    def __str__(self):
        return f"Referral — {self.child.full_name} on {self.referral_date} ({self.status})"
